# Generated by Django 5.2.4 on 2025-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=85)),
                ('senha', models.CharField(max_length=15)),
                ('dtinclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
