# Generated by Django 5.2.4 on 2025-07-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('idoperacao', models.AutoField(primary_key=True, serialize=False)),
                ('parametros', models.CharField()),
                ('resultado', models.CharField()),
                ('dtinclusao', models.DateTimeField(auto_now_add=True)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
